// ─────────────────────────────────────────
//  FILMOZA – Crew Member Data
// ─────────────────────────────────────────

const CREW_DATA = [
  {
    id: 1,
    name: "Arjun Mehta",
    role: "Director of Photography",
    department: "Cinematography",
    experience: 12,
    expLevel: "senior",
    location: "Mumbai, India",
    availability: "available",
    featured: true,
    avatarColor: "#2a9d8f",
    bio: "Award-winning DP with 12 years across feature films, documentaries, and OTT originals. Known for distinctive visual storytelling rooted in natural light and bold framing.",
    skills: ["ARRI ALEXA", "Sony Venice", "Natural Light", "Color Grading", "Drone Ops", "Anamorphic"],
    projects: 47,
    awards: 4,
    reelUrl: "#",
    filmography: [
      { year: 2025, title: "Shadows & Salt", role: "Director of Photography", type: "Feature Film", awards: "Best Cinematography – IFFI" },
      { year: 2024, title: "The Quiet Shore", role: "Director of Photography", type: "OTT Series" },
      { year: 2023, title: "Arid Hymn", role: "DP", type: "Documentary", awards: "Official Selection – MAMI" },
      { year: 2022, title: "Ember Road", role: "Director of Photography", type: "Feature Film" },
    ],
    awardsList: [
      { title: "Best Cinematography", event: "IFFI 2025 – Shadows & Salt" },
      { title: "Golden Frame Award", event: "Mumbai Film Festival 2023" },
      { title: "Excellence in Craft", event: "Screen Craft Awards 2022" },
      { title: "Emerging DP Award", event: "MAMI 2019" },
    ]
  },
  {
    id: 2,
    name: "Priya Nair",
    role: "Film Editor",
    department: "Editing",
    experience: 9,
    expLevel: "senior",
    location: "Chennai, India",
    availability: "available",
    featured: true,
    avatarColor: "#e63946",
    bio: "Story-first editor with a background in classical music, bringing rhythm and precision to every cut. Experienced in drama, thriller, and non-linear narratives.",
    skills: ["Avid Media Composer", "DaVinci Resolve", "Premiere Pro", "Sound Editing", "Color", "VFX Supervision"],
    projects: 34,
    awards: 3,
    reelUrl: "#",
    filmography: [
      { year: 2026, title: "Fractured Hours", role: "Lead Editor", type: "Feature Film" },
      { year: 2025, title: "Undercurrent", role: "Editor", type: "Thriller Series", awards: "Best Edit – OTT Summit" },
      { year: 2024, title: "The Paper House", role: "Editor", type: "Feature Film" },
      { year: 2023, title: "Nerve Map", role: "Editor", type: "Documentary" },
    ],
    awardsList: [
      { title: "Best Editing", event: "OTT Summit Awards 2025" },
      { title: "Editors' Choice Award", event: "NASC Film Festival 2023" },
      { title: "Outstanding Craft", event: "Tamil Nadu State Awards 2022" },
    ]
  },
  {
    id: 3,
    name: "Kabir Sinha",
    role: "Director",
    department: "Direction",
    experience: 15,
    expLevel: "senior",
    location: "Kolkata, India",
    availability: "soon",
    featured: true,
    avatarColor: "#f4a261",
    bio: "Narrative-driven director with a focus on human stories rooted in regional realities. Festival darling with national and international recognition.",
    skills: ["Screenplay", "Actor Direction", "Visual Development", "Documentary", "Workshop Facilitation", "Post Supervision"],
    projects: 22,
    awards: 8,
    reelUrl: "#",
    filmography: [
      { year: 2025, title: "The River Speaks", role: "Director & Writer", type: "Feature Film", awards: "National Award Winner" },
      { year: 2023, title: "Dry Season", role: "Director", type: "Feature Film", awards: "Cannes – Un Certain Regard" },
      { year: 2021, title: "Letters to Maa", role: "Director", type: "Feature Film" },
      { year: 2019, title: "Still Water", role: "Director", type: "Short Film", awards: "Best Short – BAFTA nominee" },
    ],
    awardsList: [
      { title: "National Film Award – Best Direction", event: "2025" },
      { title: "Cannes – Un Certain Regard Prize", event: "2023" },
      { title: "BAFTA Nomination", event: "Best Short Film 2019" },
      { title: "Filmfare Award", event: "Best Director 2021" },
      { title: "IIFA Award", event: "Best Direction 2022" },
    ]
  },
  {
    id: 4,
    name: "Nadia Farooq",
    role: "Sound Designer",
    department: "Sound Design",
    experience: 7,
    expLevel: "mid",
    location: "Hyderabad, India",
    availability: "available",
    featured: true,
    avatarColor: "#9b5de5",
    bio: "Immersive sound designer specializing in Dolby Atmos mixes for theatres and OTT. Passionate about building sonic worlds that deepen emotional resonance.",
    skills: ["Pro Tools", "Dolby Atmos", "Foley", "ADR", "Boom Operation", "Music Supervision"],
    projects: 28,
    awards: 2,
    reelUrl: "#",
    filmography: [
      { year: 2026, title: "Echo Chamber", role: "Sound Designer", type: "Psychological Thriller" },
      { year: 2025, title: "Forest Floor", role: "Sound Designer & Mixer", type: "Documentary" },
      { year: 2024, title: "The Tide Line", role: "Sound Designer", type: "Feature Film", awards: "Best Sound – Filmfare" },
      { year: 2023, title: "Pulse", role: "Re-Recording Mixer", type: "OTT Series" },
    ],
    awardsList: [
      { title: "Best Sound Design", event: "Filmfare Awards 2024" },
      { title: "Sound Excellence Award", event: "Hyderabad Film Festival 2023" },
    ]
  },
  {
    id: 5,
    name: "Ravi Anand",
    role: "Production Designer",
    department: "Production Design",
    experience: 11,
    expLevel: "senior",
    location: "Delhi, India",
    availability: "busy",
    featured: false,
    avatarColor: "#3a86ff",
    bio: "Production designer with an architecture background. Creates worlds from scratch — from period-accurate sets to futuristic sci-fi environments.",
    skills: ["Set Design", "Art Direction", "Prop Design", "3D Visualization", "Period Authenticity", "Budget Management"],
    projects: 39,
    awards: 5,
    reelUrl: "#",
    filmography: [
      { year: 2025, title: "Raj & the Last Train", role: "Production Designer", type: "Period Drama" },
      { year: 2024, title: "Steel City", role: "Art Director", type: "Sci-Fi Feature" },
      { year: 2023, title: "Bazaar Nights", role: "Production Designer", type: "Feature Film" },
      { year: 2022, title: "Echoes of Partition", role: "Production Designer", type: "Historical Drama", awards: "National Award" },
    ],
    awardsList: [
      { title: "National Award – Best Art Direction", event: "2022" },
      { title: "Best Production Design", event: "Filmfare 2023" },
      { title: "Art Direction Excellence", event: "IFFI 2021" },
    ]
  },
  {
    id: 6,
    name: "Tanya Rodrigues",
    role: "VFX Supervisor",
    department: "VFX & Animation",
    experience: 6,
    expLevel: "mid",
    location: "Bangalore, India",
    availability: "available",
    featured: false,
    avatarColor: "#ff6b6b",
    bio: "VFX supervisor bridging the gap between the set and the digital world. Specialized in invisible VFX and environment creation for photo-realistic outputs.",
    skills: ["Nuke", "Houdini", "Maya", "Unreal Engine", "On-Set VFX Supervision", "Compositing"],
    projects: 19,
    awards: 1,
    reelUrl: "#",
    filmography: [
      { year: 2026, title: "Beyond the Frame", role: "VFX Supervisor", type: "Feature Film" },
      { year: 2025, title: "Aurora Rising", role: "Lead Compositor", type: "Sci-Fi Series" },
      { year: 2024, title: "The Last Monsoon", role: "VFX Artist", type: "Feature Film", awards: "Best VFX – Filmfare" },
      { year: 2023, title: "Hollow Ground", role: "VFX Compositor", type: "Feature Film" },
    ],
    awardsList: [
      { title: "Best Visual Effects", event: "Filmfare Awards 2024" },
    ]
  },
  {
    id: 7,
    name: "Meena Krishnan",
    role: "Costume Designer",
    department: "Costume Design",
    experience: 14,
    expLevel: "senior",
    location: "Kochi, India",
    availability: "available",
    featured: false,
    avatarColor: "#c77dff",
    bio: "Veteran costume designer with unparalleled knowledge of Indian textile traditions fused with contemporary aesthetics. NIFT graduate with a decade of feature film experience.",
    skills: ["Period Costumes", "Character Design", "Textile Research", "Budget Planning", "Team Leadership", "Sustainable Fashion"],
    projects: 52,
    awards: 6,
    reelUrl: "#",
    filmography: [
      { year: 2025, title: "Woven in Gold", role: "Costume Designer", type: "Historical Drama" },
      { year: 2024, title: "The Last Maharani", role: "Costume Designer", type: "Period Epic", awards: "National Award" },
      { year: 2022, title: "City of Threads", role: "Costume Designer", type: "Contemporary Drama" },
      { year: 2020, title: "Songs of Kerala", role: "Costume Designer", type: "Feature Film" },
    ],
    awardsList: [
      { title: "National Award – Best Costume Design", event: "2024" },
      { title: "Kerala State Film Award", event: "2022, 2020" },
      { title: "Filmfare Award", event: "Best Costume Design 2021" },
    ]
  },
  {
    id: 8,
    name: "Siddharth Jha",
    role: "Gaffer / Lighting Director",
    department: "Cinematography",
    experience: 8,
    expLevel: "mid",
    location: "Pune, India",
    availability: "soon",
    featured: false,
    avatarColor: "#e9c46a",
    bio: "Master gaffer with deep knowledge of LED tech, natural light augmentation, and large-scale production lighting. Reliable, fast, and safety-conscious on every set.",
    skills: ["LED Technology", "Practical Lighting", "HMI", "Safety Protocols", "Generator Ops", "Rigging"],
    projects: 31,
    awards: 0,
    reelUrl: "#",
    filmography: [
      { year: 2026, title: "Dawn Protocol", role: "Gaffer", type: "Action Thriller" },
      { year: 2025, title: "Mango Rain", role: "Gaffer", type: "Drama" },
      { year: 2024, title: "City Pulse", role: "Best Boy Electric", type: "Series" },
      { year: 2023, title: "Undying Light", role: "Gaffer", type: "Feature Film" },
    ],
    awardsList: []
  },
  {
    id: 9,
    name: "Anjali Desai",
    role: "Hair & Makeup Artist",
    department: "Hair & Makeup",
    experience: 5,
    expLevel: "mid",
    location: "Ahmedabad, India",
    availability: "available",
    featured: false,
    avatarColor: "#fb8500",
    bio: "Creative makeup artist trained in prosthetics, SFX, and high-fashion beauty. Brings characters to life with precision, speed, and an eye for authenticity.",
    skills: ["Prosthetics", "SFX Makeup", "Period Makeup", "Hair Styling", "Wig Work", "Beauty"],
    projects: 17,
    awards: 1,
    reelUrl: "#",
    filmography: [
      { year: 2025, title: "Bone Deep", role: "SFX Makeup Lead", type: "Horror Feature" },
      { year: 2025, title: "Legacy of Dust", role: "Makeup Artist", type: "Period Drama" },
      { year: 2024, title: "City Saints", role: "Key Makeup Artist", type: "Series" },
      { year: 2023, title: "Face Forward", role: "Makeup Artist", type: "Documentary" },
    ],
    awardsList: [
      { title: "Best Makeup Design", event: "Ahmedabad Film Festival 2023" },
    ]
  },
  {
    id: 10,
    name: "Omar Rasheed",
    role: "Screenwriter",
    department: "Direction",
    experience: 10,
    expLevel: "senior",
    location: "Lucknow, India",
    availability: "available",
    featured: false,
    avatarColor: "#06d6a0",
    bio: "Versatile screenwriter across genres — from social dramas to dark comedies and political thrillers. Strong ear for dialogue with a focus on character-driven stories.",
    skills: ["Feature Screenplay", "TV Writing", "Dialogue", "Story Development", "Story Doctoring", "Adaptations"],
    projects: 26,
    awards: 3,
    reelUrl: "#",
    filmography: [
      { year: 2026, title: "The Ballot", role: "Writer", type: "Political Thriller" },
      { year: 2025, title: "Noor", role: "Screenwriter", type: "Drama", awards: "Best Screenplay – IFFI" },
      { year: 2024, title: "Laughing Stock", role: "Writer", type: "Dark Comedy Series" },
      { year: 2022, title: "The Settlement", role: "Writer & Story", type: "Feature Film" },
    ],
    awardsList: [
      { title: "Best Screenplay", event: "IFFI 2025" },
      { title: "Writers' Guild Award", event: "2023" },
      { title: "Jio MAMI Best Script", event: "2021" },
    ]
  },
  {
    id: 11,
    name: "Deepika Sharma",
    role: "Line Producer",
    department: "Direction",
    experience: 3,
    expLevel: "entry",
    location: "Jaipur, India",
    availability: "available",
    featured: false,
    avatarColor: "#ef476f",
    bio: "Detail-oriented line producer managing budgets, schedules, and logistics for films and series. Experienced in both location and studio productions.",
    skills: ["Budgeting", "Scheduling", "Location Management", "Vendor Relations", "Crew Hiring", "Production Insurance"],
    projects: 9,
    awards: 0,
    reelUrl: "#",
    filmography: [
      { year: 2026, title: "Blue Raven", role: "Line Producer", type: "Feature Film" },
      { year: 2025, title: "Terrain", role: "Associate Producer", type: "Documentary" },
      { year: 2024, title: "The Grand List", role: "Production Manager", type: "Short Film" },
    ],
    awardsList: []
  },
  {
    id: 12,
    name: "Vinay Chopra",
    role: "Music Composer",
    department: "Sound Design",
    experience: 13,
    expLevel: "senior",
    location: "Mumbai, India",
    availability: "soon",
    featured: false,
    avatarColor: "#118ab2",
    bio: "Film composer blending classical Indian instruments with orchestral and electronic music. Known for haunting, emotionally resonant scores that never overpower the story.",
    skills: ["Orchestral Composition", "Electronic Score", "Live Recording", "Indian Classical", "Sync Licensing", "Logic Pro X"],
    projects: 41,
    awards: 7,
    reelUrl: "#",
    filmography: [
      { year: 2026, title: "The River Speaks", role: "Music Composer", type: "Feature Film" },
      { year: 2025, title: "Embers", role: "Original Score", type: "Drama Feature", awards: "National Award" },
      { year: 2024, title: "Hawa", role: "Music Director", type: "Feature Film" },
      { year: 2023, title: "Khwaab", role: "Composer", type: "Anthology Series" },
    ],
    awardsList: [
      { title: "National Award – Best Music Direction", event: "2025" },
      { title: "Filmfare Award", event: "Best Background Score 2024, 2022" },
      { title: "IIFA Award", event: "Best Music 2023" },
    ]
  }
];
